# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08lp.proto\x12\x06\x63mu.lp\"4\n\x05Image\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"c\n\x06\x41\x63tion\x12\x12\n\ntrajectory\x18\x01 \x03(\x02\x12\x12\n\nconfidence\x18\x02 \x03(\x02\x12\x11\n\ttimesteps\x18\x03 \x01(\x05\x12\x0f\n\x07weights\x18\x04 \x03(\x02\x12\r\n\x05phase\x18\x05 \x01(\x02\"c\n\x05State\x12\x1c\n\x05image\x18\x01 \x01(\x0b\x32\r.cmu.lp.Image\x12\x10\n\x08language\x18\x02 \x01(\t\x12\r\n\x05robot\x18\x03 \x03(\x02\x12\r\n\x05reset\x18\x04 \x01(\x08\x12\x0c\n\x04plot\x18\x05 \x01(\x08\x32\x36\n\x08LPPolicy\x12*\n\x07Predict\x12\r.cmu.lp.State\x1a\x0e.cmu.lp.Action\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMAGE._serialized_start=20
  _IMAGE._serialized_end=72
  _ACTION._serialized_start=74
  _ACTION._serialized_end=173
  _STATE._serialized_start=175
  _STATE._serialized_end=274
  _LPPOLICY._serialized_start=276
  _LPPOLICY._serialized_end=330
# @@protoc_insertion_point(module_scope)
